spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RHMAccounting/spring-allacc
          search-paths:
            - "config-files/{application}/{profile}"
            - "config-files/global/{profile}"