spring:
  kafka:
    bootstrap-servers: 192.168.99.100:9092
    topic:
      userCreated: USER_CREATED_TOPIC


security:
  oauth2:
    client:
      clientId: rhm-gateway
      clientSecret: be20f0a6-40dc-4e9b-a469-771685f0e613
      accessTokenUri: http://localhost:8180/auth/realms/RHM/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8180/auth/realms/RHM/protocol/openid-connect/auth
      token-name: access_token
      authenticationScheme: header
      clientAuthenticationScheme: header
    resource:
      userInfoUri: http://localhost:8180/auth/realms/RHM/protocol/openid-connect/userinfo